id: I2D45CE66
default_language: zh
source: https://www2.hf.uio.no/polyglotta/index.php?page=library&bid=2
initial_creation_type: input
imported: 2023-02-09 14:37:40.237004
last_modified: 2023-02-09 14:37:40.237104
source_metadata:
  title: Vimalakīrtinirdeśa
  language: zh
bases:
  0CDD:
    base_file: 0CDD.txt
    order: 1
copyright:
  status: Unknown
  notice: ''
